### PR TITLE
Support Symfony 7

### PR DESCRIPTION
**Pull request by ttomdewit**
Add ^7 version constraint to composer.json

### CODE REVIEW

**Comment by ttomdewit** [comment]
When I try to install locally it fails on `Installing apis-guru/openapi-directory (1.0.0): Cloning openapi3.0.0` (it times out after 5 minutes/300 seconds). Will try again tomorrow 😄.

**Comment by WyriHaximus** [comment]
> When I try to install locally it fails on `Installing apis-guru/openapi-directory (1.0.0): Cloning openapi3.0.0` (it times out after 5 minutes/300 seconds). Will try again tomorrow 😄.

~~Have you tried installing with `--prefer-dist` suggesting to composer to download a zip file when possible?~~ Nevermind, it's in composer.json, doubt it will be picked up for that.

**Comment by ttomdewit** [comment]
> > When I try to install locally it fails on `Installing apis-guru/openapi-directory (1.0.0): Cloning openapi3.0.0` (it times out after 5 minutes/300 seconds). Will try again tomorrow 😄.
> 
> ~Have you tried installing with `--prefer-dist` suggesting to composer to download a zip file when possible?~ Nevermind, it's in composer.json, doubt it will be picked up for that.

Nope, unfortunately doesn't work (as you thought so yourself - I did wish to confirm, though).

**Comment by ttomdewit** [comment]
The method described in #16 works. I have successfully installed all dependencies locally.

**Comment by ttomdewit** [comment]
@DEVizzent Hi 👋 Anything I can do to get this reviewed? 😃 I apologise if this sounds pushy, I do not wish to convey that tone.

**Review by DEVizzent — APPROVED** [review]
Thank you for the update

**Comment by DEVizzent** [comment]
> @DEVizzent Hi 👋 Anything I can do to get this reviewed? 😃 I apologise if this sounds pushy, I do not wish to convey that tone. 

No problem. Thank you so much for ping me.

**Comment by ttomdewit** [comment]
@DEVizzent Thanks for merging!

**Comment by DEVizzent** [comment]
@ttomdewit You are welcome I will prepare a release for next week ;)

**Comment by KentarouTakeda** [comment]
@DEVizzent 
Hi! Could you please publish this version?

**Comment by ttomdewit** [comment]
@KentarouTakeda Thanks for the reminder!

@DEVizzent In another PR you mentioned you weren't disturbed by pings, so here I go: would it be possible to tag a new release, please? 😃

**Comment by DEVizzent** [comment]
I have as not read as a TODO. And yes, pinging is welcome.

I released the new version. Enjoy and sorry for delay it.

**Pull request merged**
